import { useCallback,useEffect,useMemo,useState } from 'react'
import { ArrowLeft,ArrowRight,Bot,CheckCircle2,Copy,GitPullRequest,RefreshCw,Search,Server,Wifi } from 'lucide-react'
import { mcJson } from '../mission-control/api'
import { connectRealtime } from '../mission-control/realtime'
import { missionRoles } from '../mission-control/auth'

type Repo={repository:string;full_name:string;planning:string;sync_state:string;open_prs:number|null;ci_state:string;active_agents:number;wip_percent:number;certified_tasks:number;total_tasks:number;remote_head_sha?:string;last_synced_at?:string;progress_dimensions?:Record<string,number|null>;progress_dimension_basis?:Record<string,string>}
type Agent={agent_id:string;provider:string;agent_type:string;repository?:string;area_id?:string;subarea_id?:string;task_id?:string;state?:string;heartbeat_at?:string;workstation?:string}

export function MissionControl(){
 const [repos,setRepos]=useState<Repo[]>([]),[agents,setAgents]=useState<Agent[]>([]),[live,setLive]=useState(false)
 const [query,setQuery]=useState(''),[selected,setSelected]=useState<Repo|null>(null),[tab,setTab]=useState<'live'|'repositories'|'work'|'prs'>('live')
 const [events,setEvents]=useState<{time:string;message:string}[]>([])
 const [refreshing,setRefreshing]=useState(false)
 const [taskInfo,setTaskInfo]=useState<any>(null)
 const [repoTasks,setRepoTasks]=useState<any[]>([])
 const [localWork,setLocalWork]=useState<any[]>([])
 const [copied,setCopied]=useState(false)
 const [now,setNow]=useState(()=>Date.now())
 const [loading,setLoading]=useState(true),[error,setError]=useState(''),[lastSynced,setLastSynced]=useState<Date|null>(null)
 const [activeAgent,setActiveAgent]=useState<Agent|null>(null)
 const [apiContract,setApiContract]=useState<unknown>(null),[contractOpen,setContractOpen]=useState(false)
 const [initialRepository]=useState(()=>new URLSearchParams(window.location.search).get('repository'))
 const load=useCallback(async():Promise<boolean>=>{
  try {
   const [r,a]=await Promise.all([mcJson('/platform/v1/dashboard/repositories'),mcJson('/platform/v1/dashboard/agents')])
   const next:Repo[]=Array.isArray(r.repositories)?r.repositories:[]
   setRepos(next);setAgents(Array.isArray(a.agents)?a.agents:[])
   const wanted=selected?.repository||initialRepository
   if(wanted){
    const record=next.find(x=>x.repository===wanted)
    if(record)setSelected(record)
    if(record){
     const name=encodeURIComponent(wanted)
     const [tasks,work]=await Promise.all([mcJson('/platform/v1/dashboard/tasks?repository='+name),mcJson('/platform/v1/dashboard/local-work?repository='+name+'&recent_hours=48')])
     setRepoTasks(Array.isArray(tasks.tasks)?tasks.tasks:[])
     setLocalWork(Array.isArray(work.lanes)?work.lanes:[])
    }
   }
   setError('');setLastSynced(new Date());return true
  }catch(e){setError(e instanceof Error?e.message:'Mission Control could not load live data.');return false}
  finally{setLoading(false)}
 },[selected?.repository,initialRepository])
 const openRepository=(r:Repo)=>{
  setSelected(r);setTab('work');setRepoTasks([]);setLocalWork([])
  const url=new URL(window.location.href);url.searchParams.set('repository',r.repository);url.searchParams.delete('task_id')
  window.history.replaceState({},'',url.pathname+url.search+url.hash)
 }
 const githubPrUrl=(r:Repo)=>/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/.test(r.full_name||'')
  ?'https://github.com/'+r.full_name+'/pulls?q=is%3Apr+is%3Aopen':null
 useEffect(()=>{const q=new URLSearchParams(window.location.search);const id=q.get('task_id');if(!id)return;let active=true;mcJson('/platform/v1/dashboard/task?task_id='+encodeURIComponent(id)).then(x=>{if(active)setTaskInfo(x.task)}).catch(()=>{if(active)setTaskInfo(null)});return()=>{active=false}},[])
 const taskLink=taskInfo?window.location.origin+'/mission-control?repository='+encodeURIComponent(taskInfo.repository)+'&area='+encodeURIComponent(taskInfo.area)+'&subarea='+encodeURIComponent(taskInfo.sub_area)+'&task_id='+encodeURIComponent(taskInfo.task_id):''
 const copyMission=async()=>{if(!taskLink)return;try{await navigator.clipboard.writeText(taskLink);setCopied(true);setTimeout(()=>setCopied(false),1500)}catch{setError('Could not copy the mission link. Check clipboard permissions.')}}
 useEffect(()=>{const initial=window.setTimeout(()=>{void load()},0);const t=setInterval(()=>{void load()},5000);const clock=setInterval(()=>setNow(Date.now()),1000);const disconnect=connectRealtime((x)=>{const type=x.namespace&&x.event_type?x.namespace+'.'+x.event_type:(x.type||'event');const label=type+(x.payload?.repository?' · '+x.payload.repository:'')+(x.payload?.task_id?' · '+x.payload.task_id:'');setEvents(e=>[{time:new Date().toLocaleTimeString(),message:label},...e].slice(0,20));load()},(status)=>{setLive(status==='connected');if(status==='connected')setEvents(e=>[{time:new Date().toLocaleTimeString(),message:'Realtime gateway connected'},...e].slice(0,20))});return()=>{clearTimeout(initial);clearInterval(t);clearInterval(clock);disconnect()}},[load])
 const shown=useMemo(()=>repos.filter(r=>(r.repository+' '+r.full_name).toLowerCase().includes(query.toLowerCase())),[repos,query])
 const synced=repos.filter(r=>r.sync_state==='SYNCED').length,prs=repos.reduce((n,r)=>n+(r.open_prs??0),0),unverifiedPrSources=repos.filter(r=>r.open_prs==null).length
 const tone=(v:string)=>{const x=(v||'UNKNOWN').toUpperCase();if(['SYNCED','GREEN','ACTIVE','CERTIFIED','READY'].includes(x))return 'bg-emerald-950 text-emerald-300 border-emerald-800';if(['DIRTY','DIVERGED','FAILED','RED','BLOCKED','ERROR'].includes(x))return 'bg-red-950 text-red-300 border-red-800';if(['REMOTE_AHEAD','LOCAL_AHEAD','PENDING','RUNNING','PLANNED'].includes(x))return 'bg-amber-950 text-amber-300 border-amber-800';return 'bg-slate-800 text-slate-300 border-slate-700'}
 const progress=(r:Repo)=>r.total_tasks?Math.round((r.certified_tasks/r.total_tasks)*100):0
 return <main className="min-h-screen bg-slate-950 text-slate-100">
  <header className="sticky top-0 z-20 border-b border-slate-800 bg-slate-950/95 px-6 py-4 backdrop-blur">
   <div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-blue-400">Codestra Engineering Control Plane</p><h1 className="text-2xl font-semibold">Mission Control</h1><p className="mt-1 text-xs text-slate-500">RBAC: {missionRoles().join(', ')||'authentication required'} · UI {__MISSION_CONTROL_BUILD_SHA__.slice(0,8)}</p></div>
   <div className="flex flex-wrap items-center gap-2 text-xs"><div className="flex overflow-hidden rounded-lg border border-slate-700 bg-slate-900"><button title="Back" aria-label="Back" onClick={()=>window.history.back()} className="border-r border-slate-700 p-2 hover:bg-slate-800"><ArrowLeft className="h-4 w-4"/></button><button title="Forward" aria-label="Forward" onClick={()=>window.history.forward()} className="border-r border-slate-700 p-2 hover:bg-slate-800"><ArrowRight className="h-4 w-4"/></button><button title="Refresh live data" aria-label="Refresh" onClick={async()=>{setRefreshing(true);const ok=await load();setRefreshing(false);if(ok)setEvents(e=>[{time:new Date().toLocaleTimeString(),message:'Live API data refreshed'},...e].slice(0,20))}} className="p-2 hover:bg-slate-800"><RefreshCw className={"h-4 w-4 "+(refreshing?'animate-spin':'')}/></button></div><button type="button" onClick={async()=>{try{const data=await mcJson('/platform/v1/dashboard/contract');setApiContract(data);setContractOpen(true);setError('')}catch(e){setError(e instanceof Error?e.message:'Could not load the API contract.')}}} title="View authenticated dashboard API contract" className="rounded-full border border-emerald-800 bg-emerald-950 px-3 py-2 hover:bg-emerald-900"><Server className="mr-1 inline h-4 w-4"/>API contract</button><span className={"rounded-full border px-3 py-2 "+(live?'border-emerald-800 bg-emerald-950':'border-amber-800 bg-amber-950')}><Wifi className="mr-1 inline h-4 w-4"/>{live?'WS connected':'WS reconnecting'}</span></div></div>
   <nav className="mt-4 flex flex-wrap gap-2">{(['live','repositories','work','prs'] as const).map(x=><button key={x} type="button" aria-current={tab===x?"page":undefined} onClick={()=>setTab(x)} className={"rounded-lg px-4 py-2 text-sm font-semibold capitalize "+(tab===x?'bg-blue-600':'bg-slate-900 hover:bg-slate-800')}>{x==='prs'?'PR Control':x}</button>)}</nav>
  </header>
  <section className="px-6 pt-4" aria-live="polite">
   {error&&<div role="alert" className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-red-700 bg-red-950/60 p-4 text-sm"><div><b>Backend unavailable or access denied</b><p className="mt-1 text-red-200">{error}</p><p className="mt-1 text-xs text-red-300">Data is not certified as live. The control plane must expose authenticated dashboard endpoints through Caddy/Kong.</p></div><button type="button" onClick={()=>void load()} className="rounded-lg bg-red-800 px-4 py-2 font-semibold hover:bg-red-700">Retry connection</button></div>}
   {loading&&!lastSynced&&<p role="status" className="rounded-xl border border-slate-700 bg-slate-900 p-4 text-sm text-slate-300">Connecting to the Mission Control backend…</p>}
   {lastSynced&&<p className="mt-2 text-xs text-slate-400">Last confirmed API response: {lastSynced.toLocaleTimeString()}{error?' · last known values only':''}</p>}
  </section>
  {activeAgent&&<section className="px-6 pt-4" aria-label="Agent details"><div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-blue-800 bg-slate-900 p-4"><div><b className="text-blue-300">{activeAgent.agent_id}</b><p className="text-sm text-slate-300">{activeAgent.provider} · {activeAgent.agent_type} · {activeAgent.state||'UNKNOWN'}</p><p className="text-xs text-slate-400">Repository: {activeAgent.repository||'Unassigned'} · Task: {activeAgent.task_id||'No task'} · Last heartbeat: {activeAgent.heartbeat_at||'Unknown'}</p></div><div className="flex gap-2">{activeAgent.repository&&repos.find(r=>r.repository===activeAgent.repository)&&<button type="button" onClick={()=>{const r=repos.find(x=>x.repository===activeAgent.repository);if(r)openRepository(r)}} className="rounded-lg bg-blue-600 px-4 py-2 text-sm hover:bg-blue-500">Open repository work</button>}<button type="button" onClick={()=>setActiveAgent(null)} aria-label="Close agent details" className="rounded-lg border border-slate-700 px-4 py-2">Close</button></div></div></section>}
  {contractOpen&&<section className="px-6 pt-4" aria-label="Backend API contract"><div className="rounded-xl border border-blue-800 bg-slate-900 p-5"><div className="flex items-center justify-between gap-3"><h2 className="font-semibold">Authenticated backend API contract</h2><button type="button" onClick={()=>setContractOpen(false)} className="rounded-lg border border-slate-700 px-3 py-2">Close</button></div><pre className="mt-4 max-h-80 overflow-auto rounded-lg bg-slate-950 p-4 text-xs text-slate-300">{JSON.stringify(apiContract,null,2)}</pre></div></section>}
  {taskInfo&&<section className="px-6 pt-4"><div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-blue-800 bg-blue-950/40 p-4"><div><p className="text-xs font-bold uppercase tracking-widest text-blue-300">Active mission task</p><b>{taskInfo.repository} → {taskInfo.area} → {taskInfo.sub_area}</b><small className="ml-2 text-slate-400">{taskInfo.task_id}</small></div><button onClick={copyMission} className="flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2 font-semibold hover:bg-blue-500"><Copy className="h-4 w-4"/>{copied?'Copied':'Copy Mission Link'}</button></div></section>}
  {tab==='live'&&<section className="grid gap-4 px-6 pt-6 xl:grid-cols-[2fr_1fr]"><div className="rounded-xl border border-slate-800 bg-slate-900"><div className="flex items-center justify-between border-b border-slate-800 p-5"><div><p className="text-xs font-bold uppercase tracking-widest text-emerald-400">Live now</p><h2 className="text-xl font-semibold">Agent Operations</h2></div><span className={"rounded-full border px-3 py-1 text-xs "+(live?'border-emerald-800 bg-emerald-950 text-emerald-300':'border-red-800 bg-red-950 text-red-300')}>{live?'WS CONNECTED':'WS OFFLINE'}</span></div><div className="divide-y divide-slate-800">{agents.map(a=>{const age=a.heartbeat_at?Math.max(0,Math.floor((now-new Date(a.heartbeat_at).getTime())/1000)):null;return <button key={a.agent_id} type="button" onClick={()=>setActiveAgent(a)} title={"Inspect agent "+a.agent_id} className="grid w-full grid-cols-1 gap-3 p-4 text-left hover:bg-slate-800/60 sm:grid-cols-2 xl:grid-cols-[1.2fr_1fr_1.4fr_.7fr]"><span><b className="block text-blue-300">{a.agent_id}</b><small className="text-slate-500">{a.agent_type} · {a.workstation||'unassigned'}</small></span><span>{a.repository||'Available'}</span><span><b>{a.area_id||'—'} → {a.subarea_id||'—'}</b><small className="block text-slate-500">{a.task_id||'No task'}</small></span><span><b className={"rounded-full border px-2 py-1 text-xs "+tone(a.state||'UNKNOWN')}>{a.state||'UNKNOWN'}</b><small className="mt-2 block text-slate-500">{age===null?'no heartbeat':age+'s ago'}</small></span></button>})}{!agents.length&&<div className="p-6 text-sm text-slate-400">{error?'No live agent data available.':'No active agents reported by the API.'}</div>}</div></div><aside className="rounded-xl border border-slate-800 bg-slate-900"><div className="border-b border-slate-800 p-5"><p className="text-xs font-bold uppercase tracking-widest text-blue-400">Transport events</p><h2 className="text-xl font-semibold">Realtime Events</h2></div><div className="max-h-[430px] divide-y divide-slate-800 overflow-auto">{events.length?events.map((e,i)=><div key={i} className="p-4 text-sm"><b className="text-slate-300">{e.message}</b><small className="mt-1 block text-slate-500">{e.time}</small></div>):<div className="p-8 text-sm text-slate-500">Waiting for the next WebSocket event…</div>}</div></aside></section>}
  <section className="grid gap-3 p-6 md:grid-cols-4">{[[repos.length,'Repositories',Server],[synced,'Synchronized',CheckCircle2],[unverifiedPrSources?prs+'+?':prs,'Open PRs',GitPullRequest],[agents.filter(a=>!!a.heartbeat_at&&!Number.isNaN(Date.parse(a.heartbeat_at))&&now-Date.parse(a.heartbeat_at)<60000&&now-Date.parse(a.heartbeat_at)>=0).length,'Live agents',Bot]].map(([n,l,I]:any)=><div key={l} className="rounded-xl border border-slate-800 bg-slate-900 p-4"><I className="mb-3 h-5 w-5 text-blue-400"/><p className="text-2xl font-semibold">{n}</p><p className="text-xs text-slate-500">{l}</p></div>)}</section>
  {tab==='repositories'&&<section className="px-6 pb-8"><div className="mb-4 flex items-center rounded-xl border border-slate-800 bg-slate-900 px-4"><Search className="h-4 w-4 text-slate-500"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search repositories…" className="w-full bg-transparent p-3 outline-none"/></div>
   <div className="overflow-x-auto rounded-xl border border-slate-800 bg-slate-900"><div className="grid min-w-[880px] grid-cols-[2fr_repeat(6,1fr)] gap-2 border-b border-slate-800 px-4 py-3 text-xs font-bold uppercase text-slate-500"><span>Repository</span><span>Sync</span><span>PRs</span><span>CI</span><span>Agents</span><span>WIP</span><span>Certified</span></div>
   {shown.map(r=><button key={r.repository} onClick={()=>openRepository(r)} className="grid min-w-[880px] w-full grid-cols-[2fr_repeat(6,1fr)] gap-2 border-b border-slate-800 px-4 py-4 text-left text-sm hover:bg-slate-800/70"><span><b className="block text-blue-300">{r.repository}</b><small className="text-slate-500">{r.planning}</small></span><span><b className={"inline-block rounded-full border px-2 py-1 text-xs "+tone(r.sync_state)}>{r.sync_state}</b></span><span>{r.open_prs}</span><span><b className={"inline-block rounded-full border px-2 py-1 text-xs "+tone(r.ci_state)}>{r.ci_state}</b></span><span>{r.active_agents}</span><span><div className="mb-1 text-xs"><b>{r.wip_percent}%</b></div><div className="h-2 overflow-hidden rounded-full bg-slate-800"><div className="h-full bg-blue-500" style={{width:Math.min(100,r.wip_percent)+'%'}}/></div></span><span><div className="mb-1 flex justify-between text-xs"><b>{progress(r)}%</b><small>{r.certified_tasks}/{r.total_tasks}</small></div><div className="h-2 overflow-hidden rounded-full bg-slate-800"><div className="h-full bg-emerald-500" style={{width:progress(r)+'%'}}/></div></span></button>)}{!shown.length&&<p className="p-6 text-sm text-slate-400">{error?'Repository list unavailable.':'No repositories match your search.'}</p>}</div></section>}
  {tab==='work'&&<section className="space-y-4 px-6 pb-8">
   <div className="rounded-xl border border-slate-800 bg-slate-900 p-6"><p className="text-xs font-bold uppercase tracking-widest text-blue-400">Program Agent Brief</p><h2 className="mt-1 text-xl font-semibold">{selected?selected.repository:'Select a repository'} Development Plan</h2><p className="mt-2 text-sm text-slate-400">This view answers the questions every implementation/review/testing agent must know before touching code.</p></div>
   {selected&&<div className="rounded-xl border border-slate-800 bg-slate-900 p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-emerald-400">Live Router Tasks</p><h3 className="text-lg font-semibold">{selected.repository} missions</h3></div><b>{repoTasks.length} tasks</b></div><div className="mt-4 grid gap-3 lg:grid-cols-2">{repoTasks.slice(0,40).map(t=>{const u=window.location.origin+'/mission-control?repository='+encodeURIComponent(t.repository)+'&area='+encodeURIComponent(t.area)+'&subarea='+encodeURIComponent(t.sub_area)+'&task_id='+encodeURIComponent(t.task_id);return <article key={t.task_id} className="rounded-lg border border-slate-700 bg-slate-950 p-4"><div className="flex justify-between gap-2"><div><b className="text-blue-300">{t.task_id}</b><p className="text-sm">{t.area} → {t.sub_area}</p></div><span className={"h-fit rounded-full border px-2 py-1 text-xs "+(t.execution_ready?'border-emerald-800 text-emerald-300':'border-amber-800 text-amber-300')}>{t.execution_ready?'READY':'AUTHORITY NEEDED'}</span></div><p className="mt-2 text-xs text-slate-400">{t.execution_contract?.stage||t.required_skills?.join(', ')||'task'} · {t.completion_percent}%</p><a href={u} className="mt-3 inline-flex items-center gap-2 rounded-lg bg-blue-600 px-3 py-2 text-sm font-semibold hover:bg-blue-500">Open mission task <ArrowRight className="h-4 w-4"/></a></article>})}</div></div>}
   {selected&&<div className="rounded-xl border border-slate-800 bg-slate-900 p-6"><p className="text-xs font-bold uppercase tracking-widest text-violet-400">Evidence dimensions</p><h3 className="text-lg font-semibold">Independent launch signals</h3><div className="mt-4 grid gap-3 md:grid-cols-3 xl:grid-cols-6">{['existence','completeness','correctness','integration','security','operability'].map(k=>{const v=selected.progress_dimensions?.[k];return <div key={k} className="rounded-lg border border-slate-700 bg-slate-950 p-3"><p className="text-xs uppercase text-slate-500">{k}</p><b className="text-xl">{v==null?'—':v+'%'}</b><p className="mt-1 text-[11px] text-slate-600">{selected.progress_dimension_basis?.[k]||'No bound evidence'}</p></div>})}</div></div>}
   {selected&&<div className="rounded-xl border border-slate-800 bg-slate-900 p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-amber-400">Local Work Recovery</p><h3 className="text-lg font-semibold">Unreported / reconciliation lanes</h3></div><b>{localWork.filter(x=>x.classification!=='REPRESENTED').length} attention</b></div><div className="mt-4 grid gap-3 lg:grid-cols-2">{localWork.filter(x=>x.classification!=='REPRESENTED').slice(0,20).map((x:any)=><article key={x.worktree} className="rounded-lg border border-slate-700 bg-slate-950 p-4"><div className="flex justify-between gap-2"><div><b className="text-slate-200">{x.branch}</b><p className="mt-1 break-all text-xs text-slate-500">{x.head}</p></div><span className="h-fit rounded-full border border-amber-800 px-2 py-1 text-xs text-amber-300">{x.classification}</span></div><p className="mt-2 text-sm text-slate-400">{x.reason}</p><p className="mt-2 break-all text-xs text-slate-600">{x.worktree}</p></article>)}</div>{localWork.filter(x=>x.classification!=='REPRESENTED').length===0&&<p className="mt-4 text-sm text-emerald-300">No recent unpublished or dirty local lane detected for this repository.</p>}</div>}
   <div className="grid gap-4 xl:grid-cols-3">
    {[['1 · Mission / Goal','What are we building and why?','Mission Architect freezes the repository goal, success criteria, constraints and definition of done.'],
      ['2 · Main Sections','What major systems must be completed?','Repository-specific areas such as Application, Identity, Data, Integrations, Runtime, Observability and Delivery.'],
      ['3 · Subsections','What part of this section is next?','Each main section is decomposed into ordered foundations. A subsection must be ready before dependent features fan out.'],
      ['4 · Features','What user/system capability are we implementing?','Features live under a subsection. API, UI, database and integration work are implementation facets of the feature—not competing top-level areas.'],
      ['5 · Atomic Tasks','What exactly does this agent own?','One narrow, leased task with branch, worktree, base SHA, dependencies, collision keys and required skills.'],
      ['6 · Evidence / Done','How do we prove completion?','Implementation → Review → Repair → Testing → CI → Merge → Post-merge verification → Certified evidence.']
     ].map(([n,q,a])=><article key={n} className="rounded-xl border border-slate-800 bg-slate-900 p-5"><p className="text-xs font-bold text-blue-400">{n}</p><h3 className="mt-2 font-semibold">{q}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{a}</p></article>)}
   </div>
   <div className="rounded-xl border border-slate-800 bg-slate-900 p-6"><h3 className="font-semibold">Design plan / authority flow</h3><div className="mt-5 flex flex-wrap items-center gap-2 text-sm">{['Mission','Section','Subsection','Feature','Atomic task','Implementation','Review','Testing','CI','Merge','Certified'].map((x,i)=><span key={x} className="flex items-center gap-2"><b className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2">{x}</b>{i<10&&<span className="text-slate-600">→</span>}</span>)}</div><p className="mt-5 text-sm text-slate-400">The Router only assigns READY atomic tasks. Parent foundations and dependencies control readiness. Progress is derived from task/evidence state; agents do not type percentages manually.</p></div>
   <div className="grid gap-4 lg:grid-cols-2"><div className="rounded-xl border border-slate-800 bg-slate-900 p-6"><h3 className="font-semibold">Agent must answer before coding</h3><div className="mt-4 space-y-2 text-sm text-slate-300">{['What repository and mission am I in?','What section → subsection → feature owns this task?','What exact task and definition of done do I own?','What branch, worktree and base SHA am I authorized to use?','What dependencies/collision keys block me?','What APIs/routes/data contracts are affected?','What tests/evidence are mandatory?','Who receives my handoff next?'].map(x=><p key={x}>✓ {x}</p>)}</div></div><div className="rounded-xl border border-slate-800 bg-slate-900 p-6"><h3 className="font-semibold">Current repository state</h3>{selected?<div className="mt-4 grid grid-cols-2 gap-3 text-sm">{[['Repository',selected.repository],['Planning',selected.planning],['Sync',selected.sync_state],['CI',selected.ci_state],['Open PRs',selected.open_prs],['Agents',selected.active_agents]].map(([a,b])=><div key={a} className="rounded-lg bg-slate-950 p-3"><p className="text-xs text-slate-500">{a}</p><b>{b}</b></div>)}</div>:<p className="mt-4 text-sm text-amber-300">Choose a repository from Repositories to load its actual mission hierarchy.</p>}</div></div>
  </section>}
  {tab==='prs'&&<section className="space-y-4 px-6 pb-8"><div className="rounded-xl border border-slate-800 bg-slate-900 p-6"><GitPullRequest className="mb-3 h-6 w-6 text-blue-400"/><h2 className="text-xl font-semibold">PR Control Center</h2><p className="mt-2 text-sm text-slate-400">The backend confirms {prs} open pull requests where counts are available. {unverifiedPrSources>0?unverifiedPrSources+' repositories have unverified PR counts.':repos.length+' repositories synchronized.'} Open each repository's current PR queue in GitHub; no unverified PR status is fabricated.</p></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{repos.filter(r=>(r.open_prs??0)>0||r.open_prs==null).sort((a,b)=>(b.open_prs??0)-(a.open_prs??0)).map(r=><article key={r.repository} className="rounded-xl border border-slate-800 bg-slate-900 p-5"><div className="flex justify-between gap-3"><div><b className="text-blue-300">{r.repository}</b><p className="text-xs text-slate-400">{r.full_name}</p></div><span className="h-fit rounded-lg border border-slate-700 px-3 py-1 text-sm">{r.open_prs==null?'Not verified':r.open_prs+' open'}</span></div><div className="mt-4 flex flex-wrap gap-2">{githubPrUrl(r)&&<a href={githubPrUrl(r)!} rel="noopener noreferrer" target="_blank" className="rounded-lg bg-blue-600 px-3 py-2 text-sm font-semibold hover:bg-blue-500">Review PRs ↗</a>}<button type="button" onClick={()=>openRepository(r)} className="rounded-lg border border-slate-700 px-3 py-2 text-sm hover:bg-slate-800">View work</button></div></article>)}</div>{!repos.some(r=>(r.open_prs??0)>0||r.open_prs==null)&&<p className="rounded-xl border border-slate-800 bg-slate-900 p-5 text-sm text-slate-400">{error?'PR counts unavailable until the API reconnects.':'No open PRs reported by the connected API.'}</p>}</section>}
  {selected&&tab==='repositories'&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4" onClick={()=>setSelected(null)}><section onClick={e=>e.stopPropagation()} className="w-full max-w-2xl rounded-2xl border border-slate-700 bg-slate-900 p-6"><div className="flex justify-between"><div><p className="text-xs uppercase tracking-widest text-blue-400">Repository control</p><h2 className="text-2xl font-semibold">{selected.repository}</h2></div><button onClick={()=>setSelected(null)}>✕</button></div><div className="mt-6 grid grid-cols-2 gap-3 text-sm">{[['Sync',selected.sync_state],['CI',selected.ci_state],['Open PRs',selected.open_prs],['Agents',selected.active_agents],['WIP',selected.wip_percent+'%'],['Certified',selected.certified_tasks+'/'+selected.total_tasks]].map(([a,b])=><div className="rounded-lg bg-slate-950 p-3" key={a}><p className="text-slate-500">{a}</p><b>{b}</b></div>)}</div><div className="mt-5 flex gap-2"><button onClick={()=>{setTab('work');setSelected(null)}} className="rounded-lg bg-blue-600 px-4 py-2">Open work</button><button onClick={()=>{setTab('prs');setSelected(null)}} className="rounded-lg border border-slate-700 px-4 py-2">Open PRs</button></div></section></div>}
 </main>
}
