import { useEffect, useState } from 'react'
import { Bell, Bot, CheckCircle2, GitPullRequest, Radio, Route, ShieldCheck, Wrench } from 'lucide-react'

type Agent={agent_id:string;provider:string;agent_type:string;repository?:string;area_id?:string;subarea_id?:string;task_id?:string;state?:string;workstation?:string}
const sections=['Core','Features','APIs','URLs / Routes','Workstations','Security','Data','Adapters','Observability','Delivery / CI']

export function MissionControl(){
 const [agents,setAgents]=useState<Agent[]>([])
 const [live,setLive]=useState(false)
 const [selected,setSelected]=useState<Agent|null>(null)
 const params=new URLSearchParams(window.location.search)
 const assignment={repository:params.get('repository'),area:params.get('area'),subarea:params.get('subarea'),taskId:params.get('task_id'),agentId:params.get('agent_id')}
 const hasAssignment=Boolean(assignment.repository&&assignment.area&&assignment.subarea&&assignment.taskId)
 useEffect(()=>{const load=()=>fetch('http://127.0.0.1:8790/platform/v1/dashboard/agents').then(r=>r.json()).then(x=>setAgents(x.agents||[])).catch(()=>{});load();const t=setInterval(load,5000);const ws=new WebSocket('ws://127.0.0.1:8791');ws.onopen=()=>setLive(true);ws.onclose=()=>setLive(false);ws.onmessage=()=>load();return()=>{clearInterval(t);ws.close()}},[])
 return <main className="min-h-screen bg-slate-950 text-slate-100">
  {hasAssignment&&<section data-testid="assignment-context" className="border-b border-blue-700 bg-blue-950/60 px-8 py-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-widest text-blue-300">Scoped assignment loaded</p><p className="mt-1 font-semibold">{assignment.repository} → {assignment.area} → {assignment.subarea} → {assignment.taskId}</p><p className="text-xs text-slate-400">This task reference is explicit and will not expand to the whole repository.</p></div><div className="flex gap-2"><button onClick={()=>navigator.clipboard.writeText(window.location.href)} className="rounded-lg border border-blue-700 px-3 py-2 text-sm">Copy link</button><button className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold">Claim task</button></div></div></section>}
  <header className="border-b border-slate-800 bg-slate-900/90 px-8 py-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-blue-400">Codestra Engineering Control Plane</p><h1 className="mt-1 text-3xl font-semibold">Agent Brain Mission Control</h1><p className="mt-1 text-sm text-slate-400">Mission Architect → Router → Implementation → Review → Testing → Certification</p></div><div className="flex gap-2"><span className="rounded-full border border-slate-700 px-3 py-2 text-xs"><Radio className="mr-2 inline h-4 w-4 text-emerald-400"/>{live?'Realtime connected':'Realtime reconnecting'}</span><button className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold"><Bell className="mr-2 inline h-4 w-4"/>Notifications</button></div></div></header>
  <section className="grid gap-4 p-6 md:grid-cols-4">
   {[['Active agents',agents.length,Bot],['Implementation','Continuous',Wrench],['Evidence gates','Enforced',ShieldCheck],['PR / CI','Synchronized',GitPullRequest]].map(([a,b,I]:any)=><div className="rounded-2xl border border-slate-800 bg-slate-900 p-5" key={a}><I className="mb-4 h-5 w-5 text-blue-400"/><p className="text-xs text-slate-500">{a}</p><p className="mt-1 text-2xl font-semibold">{b}</p></div>)}
  </section>
  <section className="px-6"><div className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="mb-5 flex justify-between"><div><h2 className="font-semibold">Mission journey</h2><p className="text-xs text-slate-500">Certified evidence moves the delivery journey.</p></div><span className="text-xs text-blue-400">WIP / Certified tracked separately</span></div><div className="flex overflow-x-auto pb-2">{sections.map((s,i)=><div className="min-w-32 text-center" key={s}><div className="mx-auto grid h-10 w-10 place-items-center rounded-full bg-slate-800 text-sm font-bold text-blue-300">{i+1}</div><p className="mt-2 text-xs">{s}</p>{i<sections.length-1&&<div className="relative -right-16 -top-8 h-px bg-slate-700"/>}</div>)}</div></div></section>
  <section className="grid gap-4 p-6 xl:grid-cols-[2fr_1fr]">
   <div className="rounded-2xl border border-slate-800 bg-slate-900"><div className="border-b border-slate-800 p-5"><h2 className="font-semibold">Live agent lanes</h2><p className="text-xs text-slate-500">Implementation, review, testing and supervisor lanes update through Agent Brain.</p></div>{agents.length===0?<div className="p-10 text-center text-slate-500"><Bot className="mx-auto mb-3 h-8 w-8"/>No agents registered yet. The control plane is online and waiting for governed assignments.</div>:agents.map(a=><button onClick={()=>setSelected(a)} className="grid w-full grid-cols-4 gap-3 border-b border-slate-800 px-5 py-4 text-left text-sm transition hover:bg-slate-800/70 focus:bg-slate-800" key={a.agent_id}><b className="text-blue-300">{a.agent_id}</b><span>{a.repository||'Available'}</span><span>{a.area_id||a.agent_type}</span><span>{a.state||'READY'}</span></button>)}</div>
   <div className="space-y-4"><div className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><h2 className="font-semibold">Development answers</h2><div className="mt-4 space-y-3 text-sm text-slate-300">{['Mission frozen and versioned','Exact SHA / lane guard','Required headers checked','CI gates enforced','Stopped agents replaced','Postman + PostgreSQL when required'].map(x=><p key={x}><CheckCircle2 className="mr-2 inline h-4 w-4 text-emerald-400"/>{x}</p>)}</div></div><div className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><Route className="mb-3 h-5 w-5 text-blue-400"/><h2 className="font-semibold">Assignment links</h2><p className="mt-2 text-sm text-slate-400">Repo → Area → Sub-area → Mission → Atomic task. Copyable scoped links will dispatch only after governance checks.</p></div></div>
  </section>
  {selected&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/60 p-4" onClick={()=>setSelected(null)}><section onClick={e=>e.stopPropagation()} className="w-full max-w-3xl rounded-2xl border border-slate-700 bg-slate-900 p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-xs uppercase tracking-widest text-blue-400">Agent lane detail</p><h2 className="mt-1 text-2xl font-semibold">{selected.agent_id}</h2><p className="text-sm text-slate-400">{selected.provider} · {selected.agent_type} · {selected.state||'READY'}</p></div><button onClick={()=>setSelected(null)} className="rounded-lg border border-slate-700 px-3 py-2">Close</button></div><div className="mt-6 grid gap-4 md:grid-cols-2"><div className="rounded-xl bg-slate-950 p-4"><h3 className="font-semibold">Mission placement</h3><dl className="mt-3 space-y-2 text-sm text-slate-300"><div><dt className="text-slate-500">Repository</dt><dd>{selected.repository||'Available'}</dd></div><div><dt className="text-slate-500">Area / subsection</dt><dd>{selected.area_id||'—'} / {selected.subarea_id||'—'}</dd></div><div><dt className="text-slate-500">Atomic task</dt><dd>{selected.task_id||'—'}</dd></div><div><dt className="text-slate-500">Workstation</dt><dd>{selected.workstation||'—'}</dd></div></dl></div><div className="rounded-xl bg-slate-950 p-4"><h3 className="font-semibold">Design logic</h3><p className="mt-3 text-sm text-slate-300">This lane implements one frozen atomic task. Mission Architect owns goal and architecture; Router owns assignment and dependencies; Review challenges implementation; Testing produces required evidence; Certification advances only after CI, merge and post-merge proof.</p><div className="mt-4 flex flex-wrap gap-2"><button className="rounded-lg bg-blue-600 px-3 py-2 text-sm font-semibold">Open mission</button><button className="rounded-lg border border-slate-700 px-3 py-2 text-sm">Copy assignment link</button><button className="rounded-lg border border-slate-700 px-3 py-2 text-sm">View evidence</button></div></div></div></section></div>}
 </main>
}
